import type { DrawCategory } from "@/lib/crs/ruleset/types";

// The full 2021 National Occupational Classification unit-group list — every
// NOC code, its title, and its TEER category.
//
// Source: "Find your National Occupational Classification (NOC)" —
// https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/find-national-occupation-code.html
// Transcribed 2026-07-27. 516 unit groups.
//
// `categories` lists the category-based draws IRCC currently accepts this
// occupation for, from the separate category-based selection page. Most
// occupations have none — that is normal and correct, not missing data. All 91
// occupations named on the category page resolve to a code in this list, which
// is how the two transcriptions cross-check each other.
//
// Being on a category list is NOT eligibility. See CATEGORY_RULES in
// noc-categories.ts for the experience conditions that must also hold.

export interface Occupation {
  /** 2021 NOC unit group code. */
  noc: string;
  title: string;
  /** 2021 TEER category, 0-5. */
  teer: number;
  categories: DrawCategory[];
}

export const OCCUPATIONS: Occupation[] = [
  { noc: "00010", title: "Legislators", teer: 0, categories: [] },
  { noc: "00011", title: "Senior government managers and officials", teer: 0, categories: [] },
  { noc: "00012", title: "Senior managers - financial, communications and other business services", teer: 0, categories: ["seniorManagers"] },
  { noc: "00013", title: "Senior managers - health, education, social and community services and membership organizations", teer: 0, categories: ["seniorManagers"] },
  { noc: "00014", title: "Senior managers - trade, broadcasting and other services", teer: 0, categories: ["seniorManagers"] },
  { noc: "00015", title: "Senior managers - construction, transportation, production and utilities", teer: 0, categories: ["seniorManagers"] },
  { noc: "10010", title: "Financial managers", teer: 0, categories: [] },
  { noc: "10011", title: "Human resources managers", teer: 0, categories: [] },
  { noc: "10012", title: "Purchasing managers", teer: 0, categories: [] },
  { noc: "10019", title: "Other administrative services managers", teer: 0, categories: [] },
  { noc: "10020", title: "Insurance, real estate and financial brokerage managers", teer: 0, categories: [] },
  { noc: "10021", title: "Banking, credit and other investment managers", teer: 0, categories: [] },
  { noc: "10022", title: "Advertising, marketing and public relations managers", teer: 0, categories: [] },
  { noc: "10029", title: "Other business services managers", teer: 0, categories: [] },
  { noc: "10030", title: "Telecommunication carriers managers", teer: 0, categories: [] },
  { noc: "11100", title: "Financial auditors and accountants", teer: 1, categories: [] },
  { noc: "11101", title: "Financial and investment analysts", teer: 1, categories: [] },
  { noc: "11102", title: "Financial advisors", teer: 1, categories: [] },
  { noc: "11103", title: "Securities agents, investment dealers and brokers", teer: 1, categories: [] },
  { noc: "11109", title: "Other financial officers", teer: 1, categories: [] },
  { noc: "11200", title: "Human resources professionals", teer: 1, categories: [] },
  { noc: "11201", title: "Professional occupations in business management consulting", teer: 1, categories: [] },
  { noc: "11202", title: "Professional occupations in advertising, marketing and public relations", teer: 1, categories: [] },
  { noc: "12010", title: "Supervisors, general office and administrative support workers", teer: 2, categories: [] },
  { noc: "12011", title: "Supervisors, finance and insurance office workers", teer: 2, categories: [] },
  { noc: "12012", title: "Supervisors, library, correspondence and related information workers", teer: 2, categories: [] },
  { noc: "12013", title: "Supervisors, supply chain, tracking and scheduling coordination occupations", teer: 2, categories: [] },
  { noc: "12100", title: "Executive assistants", teer: 2, categories: [] },
  { noc: "12101", title: "Human resources and recruitment officers", teer: 2, categories: [] },
  { noc: "12102", title: "Procurement and purchasing agents and officers", teer: 2, categories: [] },
  { noc: "12103", title: "Conference and event planners", teer: 2, categories: [] },
  { noc: "12104", title: "Employment insurance and revenue officers", teer: 2, categories: [] },
  { noc: "12110", title: "Court reporters, medical transcriptionists and related occupations", teer: 2, categories: [] },
  { noc: "12111", title: "Health information management occupations", teer: 2, categories: [] },
  { noc: "12112", title: "Records management technicians", teer: 2, categories: [] },
  { noc: "12113", title: "Statistical officers and related research support occupations", teer: 2, categories: [] },
  { noc: "12200", title: "Accounting technicians and bookkeepers", teer: 2, categories: [] },
  { noc: "12201", title: "Insurance adjusters and claims examiners", teer: 2, categories: [] },
  { noc: "12202", title: "Insurance underwriters", teer: 2, categories: [] },
  { noc: "12203", title: "Assessors, business valuators and appraisers", teer: 2, categories: [] },
  { noc: "13100", title: "Administrative officers", teer: 3, categories: [] },
  { noc: "13101", title: "Property administrators", teer: 3, categories: [] },
  { noc: "13102", title: "Payroll administrators", teer: 3, categories: [] },
  { noc: "13110", title: "Administrative assistants", teer: 3, categories: [] },
  { noc: "13111", title: "Legal administrative assistants", teer: 3, categories: [] },
  { noc: "13112", title: "Medical administrative assistants", teer: 3, categories: [] },
  { noc: "13200", title: "Customs, ship and other brokers", teer: 3, categories: [] },
  { noc: "13201", title: "Production and transportation logistics coordinators", teer: 3, categories: [] },
  { noc: "14100", title: "General office support workers", teer: 4, categories: [] },
  { noc: "14101", title: "Receptionists", teer: 4, categories: [] },
  { noc: "14102", title: "Personnel clerks", teer: 4, categories: [] },
  { noc: "14103", title: "Court clerks and related court services occupations", teer: 4, categories: [] },
  { noc: "14110", title: "Survey interviewers and statistical clerks", teer: 4, categories: [] },
  { noc: "14111", title: "Data entry clerks", teer: 4, categories: [] },
  { noc: "14112", title: "Desktop publishing operators and related occupations", teer: 4, categories: [] },
  { noc: "14200", title: "Accounting and related clerks", teer: 4, categories: [] },
  { noc: "14201", title: "Banking, insurance and other financial clerks", teer: 4, categories: [] },
  { noc: "14202", title: "Collection clerks", teer: 4, categories: [] },
  { noc: "14300", title: "Library assistants and clerks", teer: 4, categories: [] },
  { noc: "14301", title: "Correspondence, publication and regulatory clerks", teer: 4, categories: [] },
  { noc: "14400", title: "Shippers and receivers", teer: 4, categories: [] },
  { noc: "14401", title: "Storekeepers and partspersons", teer: 4, categories: [] },
  { noc: "14402", title: "Production logistics workers", teer: 4, categories: [] },
  { noc: "14403", title: "Purchasing and inventory control workers", teer: 4, categories: [] },
  { noc: "14404", title: "Dispatchers", teer: 4, categories: [] },
  { noc: "14405", title: "Transportation route and crew schedulers", teer: 4, categories: [] },
  { noc: "20010", title: "Engineering managers", teer: 0, categories: [] },
  { noc: "20011", title: "Architecture and science managers", teer: 0, categories: ["stem"] },
  { noc: "20012", title: "Computer and information systems managers", teer: 0, categories: [] },
  { noc: "21100", title: "Physicists and astronomers", teer: 1, categories: [] },
  { noc: "21101", title: "Chemists", teer: 1, categories: [] },
  { noc: "21102", title: "Geoscientists and oceanographers", teer: 1, categories: [] },
  { noc: "21103", title: "Meteorologists and climatologists", teer: 1, categories: [] },
  { noc: "21109", title: "Other professional occupations in physical sciences", teer: 1, categories: [] },
  { noc: "21110", title: "Biologists and related scientists", teer: 1, categories: [] },
  { noc: "21111", title: "Forestry professionals", teer: 1, categories: [] },
  { noc: "21112", title: "Agricultural representatives, consultants and specialists", teer: 1, categories: [] },
  { noc: "21120", title: "Public and environmental health and safety professionals", teer: 1, categories: [] },
  { noc: "21200", title: "Architects", teer: 1, categories: [] },
  { noc: "21201", title: "Landscape architects", teer: 1, categories: [] },
  { noc: "21202", title: "Urban and land use planners", teer: 1, categories: [] },
  { noc: "21203", title: "Land surveyors", teer: 1, categories: [] },
  { noc: "21210", title: "Mathematicians, statisticians and actuaries", teer: 1, categories: [] },
  { noc: "21211", title: "Data scientists", teer: 1, categories: [] },
  { noc: "21220", title: "Cybersecurity specialists", teer: 1, categories: ["stem"] },
  { noc: "21221", title: "Business systems specialists", teer: 1, categories: [] },
  { noc: "21222", title: "Information systems specialists", teer: 1, categories: [] },
  { noc: "21223", title: "Database analysts and data administrators", teer: 1, categories: [] },
  { noc: "21230", title: "Computer systems developers and programmers", teer: 1, categories: [] },
  { noc: "21231", title: "Software engineers and designers", teer: 1, categories: [] },
  { noc: "21232", title: "Software developers and programmers", teer: 1, categories: [] },
  { noc: "21233", title: "Web designers", teer: 1, categories: [] },
  { noc: "21234", title: "Web developers and programmers", teer: 1, categories: [] },
  { noc: "21300", title: "Civil engineers", teer: 1, categories: ["stem"] },
  { noc: "21301", title: "Mechanical engineers", teer: 1, categories: ["stem"] },
  { noc: "21310", title: "Electrical and electronics engineers", teer: 1, categories: ["stem"] },
  { noc: "21311", title: "Computer engineers (except software engineers and designers)", teer: 1, categories: [] },
  { noc: "21320", title: "Chemical engineers", teer: 1, categories: [] },
  { noc: "21321", title: "Industrial and manufacturing engineers", teer: 1, categories: ["stem"] },
  { noc: "21322", title: "Metallurgical and materials engineers", teer: 1, categories: [] },
  { noc: "21330", title: "Mining engineers", teer: 1, categories: [] },
  { noc: "21331", title: "Geological engineers", teer: 1, categories: ["stem"] },
  { noc: "21332", title: "Petroleum engineers", teer: 1, categories: [] },
  { noc: "21390", title: "Aerospace engineers", teer: 1, categories: [] },
  { noc: "21399", title: "Other professional engineers", teer: 1, categories: [] },
  { noc: "22100", title: "Chemical technologists and technicians", teer: 2, categories: [] },
  { noc: "22101", title: "Geological and mineral technologists and technicians", teer: 2, categories: [] },
  { noc: "22110", title: "Biological technologists and technicians", teer: 2, categories: [] },
  { noc: "22111", title: "Agricultural and fish products inspectors", teer: 2, categories: [] },
  { noc: "22112", title: "Forestry technologists and technicians", teer: 2, categories: [] },
  { noc: "22113", title: "Conservation and fishery officers", teer: 2, categories: [] },
  { noc: "22114", title: "Landscape and horticulture technicians and specialists", teer: 2, categories: [] },
  { noc: "22210", title: "Architectural technologists and technicians", teer: 2, categories: [] },
  { noc: "22211", title: "Industrial designers", teer: 2, categories: [] },
  { noc: "22212", title: "Drafting technologists and technicians", teer: 2, categories: [] },
  { noc: "22213", title: "Land survey technologists and technicians", teer: 2, categories: [] },
  { noc: "22214", title: "Technical occupations in geomatics and meteorology", teer: 2, categories: [] },
  { noc: "22220", title: "Computer network and web technicians", teer: 2, categories: [] },
  { noc: "22221", title: "User support technicians", teer: 2, categories: [] },
  { noc: "22222", title: "Information systems testing technicians", teer: 2, categories: [] },
  { noc: "22230", title: "Non-destructive testers and inspectors", teer: 2, categories: [] },
  { noc: "22231", title: "Engineering inspectors and regulatory officers", teer: 2, categories: [] },
  { noc: "22232", title: "Occupational health and safety specialists", teer: 2, categories: [] },
  { noc: "22233", title: "Construction inspectors", teer: 2, categories: [] },
  { noc: "22300", title: "Civil engineering technologists and technicians", teer: 2, categories: ["stem"] },
  { noc: "22301", title: "Mechanical engineering technologists and technicians", teer: 2, categories: ["stem"] },
  { noc: "22302", title: "Industrial engineering and manufacturing technologists and technicians", teer: 2, categories: [] },
  { noc: "22303", title: "Construction estimators", teer: 2, categories: ["trades"] },
  { noc: "22310", title: "Electrical and electronics engineering technologists and technicians", teer: 2, categories: ["stem"] },
  { noc: "22311", title: "Electronic service technicians (household and business equipment)", teer: 2, categories: [] },
  { noc: "22312", title: "Industrial instrument technicians and mechanics", teer: 2, categories: [] },
  { noc: "22313", title: "Aircraft instrument, electrical and avionics mechanics, technicians and inspectors", teer: 2, categories: ["transport"] },
  { noc: "30010", title: "Managers in health care", teer: 0, categories: [] },
  { noc: "31100", title: "Specialists in clinical and laboratory medicine", teer: 1, categories: ["healthcare", "physicians"] },
  { noc: "31101", title: "Specialists in surgery", teer: 1, categories: ["healthcare", "physicians"] },
  { noc: "31102", title: "General practitioners and family physicians", teer: 1, categories: ["healthcare", "physicians"] },
  { noc: "31103", title: "Veterinarians", teer: 1, categories: ["healthcare"] },
  { noc: "31110", title: "Dentists", teer: 1, categories: ["healthcare"] },
  { noc: "31111", title: "Optometrists", teer: 1, categories: ["healthcare"] },
  { noc: "31112", title: "Audiologists and speech-language pathologists", teer: 1, categories: ["healthcare"] },
  { noc: "31120", title: "Pharmacists", teer: 1, categories: ["healthcare"] },
  { noc: "31121", title: "Dietitians and nutritionists", teer: 1, categories: ["healthcare"] },
  { noc: "31200", title: "Psychologists", teer: 1, categories: ["healthcare"] },
  { noc: "31201", title: "Chiropractors", teer: 1, categories: ["healthcare"] },
  { noc: "31202", title: "Physiotherapists", teer: 1, categories: ["healthcare"] },
  { noc: "31203", title: "Occupational therapists", teer: 1, categories: ["healthcare"] },
  { noc: "31204", title: "Kinesiologists and other professional occupations in therapy and assessment", teer: 1, categories: [] },
  { noc: "31209", title: "Other professional occupations in health diagnosing and treating", teer: 1, categories: ["healthcare"] },
  { noc: "31300", title: "Nursing coordinators and supervisors", teer: 1, categories: ["healthcare"] },
  { noc: "31301", title: "Registered nurses and registered psychiatric nurses", teer: 1, categories: ["healthcare"] },
  { noc: "31302", title: "Nurse practitioners", teer: 1, categories: ["healthcare"] },
  { noc: "31303", title: "Physician assistants, midwives and allied health professionals", teer: 1, categories: ["healthcare"] },
  { noc: "32100", title: "Opticians", teer: 2, categories: [] },
  { noc: "32101", title: "Licensed practical nurses", teer: 2, categories: ["healthcare"] },
  { noc: "32102", title: "Paramedical occupations", teer: 2, categories: ["healthcare"] },
  { noc: "32103", title: "Respiratory therapists, clinical perfusionists and cardiopulmonary technologists", teer: 2, categories: ["healthcare"] },
  { noc: "32104", title: "Animal health technologists and veterinary technicians", teer: 2, categories: ["healthcare"] },
  { noc: "32109", title: "Other technical occupations in therapy and assessment", teer: 2, categories: ["healthcare"] },
  { noc: "32110", title: "Denturists", teer: 2, categories: [] },
  { noc: "32111", title: "Dental hygienists and dental therapists", teer: 2, categories: ["healthcare"] },
  { noc: "32112", title: "Dental technologists and technicians", teer: 2, categories: [] },
  { noc: "32120", title: "Medical laboratory technologists", teer: 2, categories: ["healthcare"] },
  { noc: "32121", title: "Medical radiation technologists", teer: 2, categories: ["healthcare"] },
  { noc: "32122", title: "Medical sonographers", teer: 2, categories: ["healthcare"] },
  { noc: "32123", title: "Cardiology technologists and electrophysiological diagnostic technologists", teer: 2, categories: ["healthcare"] },
  { noc: "32124", title: "Pharmacy technicians", teer: 2, categories: ["healthcare"] },
  { noc: "32129", title: "Other medical technologists and technicians", teer: 2, categories: ["healthcare"] },
  { noc: "32200", title: "Traditional Chinese medicine practitioners and acupuncturists", teer: 2, categories: [] },
  { noc: "32201", title: "Massage therapists", teer: 2, categories: ["healthcare"] },
  { noc: "32209", title: "Other practitioners of natural healing", teer: 2, categories: [] },
  { noc: "33100", title: "Dental assistants and dental laboratory assistants", teer: 3, categories: [] },
  { noc: "33101", title: "Medical laboratory assistants and related technical occupations", teer: 3, categories: ["healthcare"] },
  { noc: "33102", title: "Nurse aides, orderlies and patient service associates", teer: 3, categories: ["healthcare"] },
  { noc: "33103", title: "Pharmacy technical assistants and pharmacy assistants", teer: 3, categories: ["healthcare"] },
  { noc: "33109", title: "Other assisting occupations in support of health services", teer: 3, categories: [] },
  { noc: "40010", title: "Government managers - health and social policy development and program administration", teer: 0, categories: [] },
  { noc: "40011", title: "Government managers - economic analysis, policy development and program administration", teer: 0, categories: [] },
  { noc: "40012", title: "Government managers - education policy development and program administration", teer: 0, categories: [] },
  { noc: "40019", title: "Other managers in public administration", teer: 0, categories: [] },
  { noc: "40020", title: "Administrators - post-secondary education and vocational training", teer: 0, categories: [] },
  { noc: "40021", title: "School principals and administrators of elementary and secondary education", teer: 0, categories: [] },
  { noc: "40030", title: "Managers in social, community and correctional services", teer: 0, categories: [] },
  { noc: "40040", title: "Commissioned police officers and related occupations in public protection services", teer: 0, categories: [] },
  { noc: "40041", title: "Fire chiefs and senior firefighting officers", teer: 0, categories: [] },
  { noc: "40042", title: "Commissioned officers of the Canadian Armed Forces", teer: 0, categories: ["militaryRecruits"] },
  { noc: "41100", title: "Judges", teer: 1, categories: [] },
  { noc: "41101", title: "Lawyers and Quebec notaries", teer: 1, categories: [] },
  { noc: "41200", title: "University professors and lecturers", teer: 1, categories: ["researchers"] },
  { noc: "41201", title: "Post-secondary teaching and research assistants", teer: 1, categories: ["researchers"] },
  { noc: "41210", title: "College and other vocational instructors", teer: 1, categories: [] },
  { noc: "41220", title: "Secondary school teachers", teer: 1, categories: ["education"] },
  { noc: "41221", title: "Elementary school and kindergarten teachers", teer: 1, categories: ["education"] },
  { noc: "41300", title: "Social workers", teer: 1, categories: ["healthcare"] },
  { noc: "41301", title: "Therapists in counselling and related specialized therapies", teer: 1, categories: ["healthcare"] },
  { noc: "41302", title: "Religious leaders", teer: 1, categories: [] },
  { noc: "41310", title: "Police investigators and other investigative occupations", teer: 1, categories: [] },
  { noc: "41311", title: "Probation and parole officers", teer: 1, categories: [] },
  { noc: "41320", title: "Educational counsellors", teer: 1, categories: [] },
  { noc: "41321", title: "Career development practitioners and career counsellors (except education)", teer: 1, categories: [] },
  { noc: "41400", title: "Natural and applied science policy researchers, consultants and program officers", teer: 1, categories: [] },
  { noc: "41401", title: "Economists and economic policy researchers and analysts", teer: 1, categories: [] },
  { noc: "41402", title: "Business development officers and market researchers and analysts", teer: 1, categories: [] },
  { noc: "41403", title: "Social policy researchers, consultants and program officers", teer: 1, categories: [] },
  { noc: "41404", title: "Health policy researchers, consultants and program officers", teer: 1, categories: [] },
  { noc: "41405", title: "Education policy researchers, consultants and program officers", teer: 1, categories: [] },
  { noc: "41406", title: "Recreation, sports and fitness policy researchers, consultants and program officers", teer: 1, categories: [] },
  { noc: "41407", title: "Program officers unique to government", teer: 1, categories: [] },
  { noc: "41409", title: "Other professional occupations in social science", teer: 1, categories: [] },
  { noc: "42100", title: "Police officers (except commissioned)", teer: 2, categories: [] },
  { noc: "42101", title: "Firefighters", teer: 2, categories: [] },
  { noc: "42102", title: "Specialized members of the Canadian Armed Forces", teer: 2, categories: ["militaryRecruits"] },
  { noc: "42200", title: "Paralegals and related occupations", teer: 2, categories: [] },
  { noc: "42201", title: "Social and community service workers", teer: 2, categories: ["healthcare"] },
  { noc: "42202", title: "Early childhood educators and assistants", teer: 2, categories: ["education"] },
  { noc: "42203", title: "Instructors of persons with disabilities", teer: 2, categories: ["education"] },
  { noc: "42204", title: "Religion workers", teer: 2, categories: [] },
  { noc: "43100", title: "Elementary and secondary school teacher assistants", teer: 3, categories: ["education"] },
  { noc: "43109", title: "Other instructors", teer: 3, categories: [] },
  { noc: "43200", title: "Sheriffs and bailiffs", teer: 3, categories: [] },
  { noc: "43201", title: "Correctional service officers", teer: 3, categories: [] },
  { noc: "43202", title: "By-law enforcement and other regulatory officers", teer: 3, categories: [] },
  { noc: "43203", title: "Border services, customs, and immigration officers", teer: 3, categories: [] },
  { noc: "43204", title: "Operations members of the Canadian Armed Forces", teer: 3, categories: ["militaryRecruits"] },
  { noc: "44100", title: "Home child care providers", teer: 4, categories: [] },
  { noc: "44101", title: "Home support workers, caregivers and related occupations", teer: 4, categories: [] },
  { noc: "44200", title: "Primary combat members of the Canadian Armed Forces", teer: 4, categories: [] },
  { noc: "45100", title: "Student monitors, crossing guards and related occupations", teer: 5, categories: [] },
  { noc: "50010", title: "Library, archive, museum and art gallery managers", teer: 0, categories: [] },
  { noc: "50011", title: "Managers - publishing, motion pictures, broadcasting and performing arts", teer: 0, categories: [] },
  { noc: "50012", title: "Recreation, sports and fitness program and service directors", teer: 0, categories: [] },
  { noc: "51100", title: "Librarians", teer: 1, categories: [] },
  { noc: "51101", title: "Conservators and curators", teer: 1, categories: [] },
  { noc: "51102", title: "Archivists", teer: 1, categories: [] },
  { noc: "51110", title: "Editors", teer: 1, categories: [] },
  { noc: "51111", title: "Authors and writers (except technical)", teer: 1, categories: [] },
  { noc: "51112", title: "Technical writers", teer: 1, categories: [] },
  { noc: "51113", title: "Journalists", teer: 1, categories: [] },
  { noc: "51114", title: "Translators, terminologists and interpreters", teer: 1, categories: [] },
  { noc: "51120", title: "Producers, directors, choreographers and related occupations", teer: 1, categories: [] },
  { noc: "51121", title: "Conductors, composers and arrangers", teer: 1, categories: [] },
  { noc: "51122", title: "Musicians and singers", teer: 1, categories: [] },
  { noc: "52100", title: "Library and public archive technicians", teer: 2, categories: [] },
  { noc: "52110", title: "Film and video camera operators", teer: 2, categories: [] },
  { noc: "52111", title: "Graphic arts technicians", teer: 2, categories: [] },
  { noc: "52112", title: "Broadcast technicians", teer: 2, categories: [] },
  { noc: "52113", title: "Audio and video recording technicians", teer: 2, categories: [] },
  { noc: "52114", title: "Announcers and other broadcasters", teer: 2, categories: [] },
  { noc: "52119", title: "Other technical and coordinating occupations in motion pictures, broadcasting and the performing arts", teer: 2, categories: [] },
  { noc: "52120", title: "Graphic designers and illustrators", teer: 2, categories: [] },
  { noc: "52121", title: "Interior designers and interior decorators", teer: 2, categories: [] },
  { noc: "53100", title: "Registrars, restorers, interpreters and other occupations related to museum and art galleries", teer: 3, categories: [] },
  { noc: "53110", title: "Photographers", teer: 3, categories: [] },
  { noc: "53111", title: "Motion pictures, broadcasting, photography and performing arts assistants and operators", teer: 3, categories: [] },
  { noc: "53120", title: "Dancers", teer: 3, categories: [] },
  { noc: "53121", title: "Actors, comedians and circus performers", teer: 3, categories: [] },
  { noc: "53122", title: "Painters, sculptors and other visual artists", teer: 3, categories: [] },
  { noc: "53123", title: "Theatre, fashion, exhibit and other creative designers", teer: 3, categories: [] },
  { noc: "53124", title: "Artisans and craftspersons", teer: 3, categories: [] },
  { noc: "53125", title: "Patternmakers - textile, leather and fur products", teer: 3, categories: [] },
  { noc: "53200", title: "Athletes", teer: 3, categories: [] },
  { noc: "53201", title: "Coaches", teer: 3, categories: [] },
  { noc: "53202", title: "Sports officials and referees", teer: 3, categories: [] },
  { noc: "54100", title: "Program leaders and instructors in recreation, sport and fitness", teer: 4, categories: [] },
  { noc: "55109", title: "Other performers", teer: 5, categories: [] },
  { noc: "60010", title: "Corporate sales managers", teer: 0, categories: [] },
  { noc: "60020", title: "Retail and wholesale trade managers", teer: 0, categories: [] },
  { noc: "60030", title: "Restaurant and food service managers", teer: 0, categories: [] },
  { noc: "60031", title: "Accommodation service managers", teer: 0, categories: [] },
  { noc: "60040", title: "Managers in customer and personal services", teer: 0, categories: [] },
  { noc: "62010", title: "Retail sales supervisors", teer: 2, categories: [] },
  { noc: "62020", title: "Food service supervisors", teer: 2, categories: [] },
  { noc: "62021", title: "Executive housekeepers", teer: 2, categories: [] },
  { noc: "62022", title: "Accommodation, travel, tourism and related services supervisors", teer: 2, categories: [] },
  { noc: "62023", title: "Customer and information services supervisors", teer: 2, categories: [] },
  { noc: "62024", title: "Cleaning supervisors", teer: 2, categories: [] },
  { noc: "62029", title: "Other services supervisors", teer: 2, categories: [] },
  { noc: "62100", title: "Technical sales specialists - wholesale trade", teer: 2, categories: [] },
  { noc: "62101", title: "Retail and wholesale buyers", teer: 2, categories: [] },
  { noc: "62200", title: "Chefs", teer: 2, categories: [] },
  { noc: "62201", title: "Funeral directors and embalmers", teer: 2, categories: [] },
  { noc: "62202", title: "Jewellers, jewellery and watch repairers and related occupations", teer: 2, categories: [] },
  { noc: "63100", title: "Insurance agents and brokers", teer: 3, categories: ["stem"] },
  { noc: "63101", title: "Real estate agents and salespersons", teer: 3, categories: [] },
  { noc: "63102", title: "Financial sales representatives", teer: 3, categories: [] },
  { noc: "63200", title: "Cooks", teer: 3, categories: [] },
  { noc: "63201", title: "Butchers - retail and wholesale", teer: 3, categories: ["trades"] },
  { noc: "63202", title: "Bakers", teer: 3, categories: [] },
  { noc: "63210", title: "Hairstylists and barbers", teer: 3, categories: [] },
  { noc: "63211", title: "Estheticians, electrologists and related occupations", teer: 3, categories: [] },
  { noc: "63220", title: "Shoe repairers and shoemakers", teer: 3, categories: [] },
  { noc: "63221", title: "Upholsterers", teer: 3, categories: [] },
  { noc: "64100", title: "Retail salespersons and visual merchandisers", teer: 4, categories: [] },
  { noc: "64101", title: "Sales and account representatives - wholesale trade (non-technical)", teer: 4, categories: [] },
  { noc: "64200", title: "Tailors, dressmakers, furriers and milliners", teer: 4, categories: [] },
  { noc: "64201", title: "Image, social and other personal consultants", teer: 4, categories: [] },
  { noc: "64300", title: "Maîtres d'hôtel and hosts/hostesses", teer: 4, categories: [] },
  { noc: "64301", title: "Bartenders", teer: 4, categories: [] },
  { noc: "64310", title: "Travel counsellors", teer: 4, categories: [] },
  { noc: "64311", title: "Pursers and flight attendants", teer: 4, categories: [] },
  { noc: "64312", title: "Airline ticket and service agents", teer: 4, categories: [] },
  { noc: "64313", title: "Ground and water transport ticket agents, cargo service representatives and related clerks", teer: 4, categories: [] },
  { noc: "64314", title: "Hotel front desk clerks", teer: 4, categories: [] },
  { noc: "64320", title: "Tour and travel guides", teer: 4, categories: [] },
  { noc: "64321", title: "Casino workers", teer: 4, categories: [] },
  { noc: "64322", title: "Outdoor sport and recreational guides", teer: 4, categories: [] },
  { noc: "64400", title: "Customer services representatives - financial institutions", teer: 4, categories: [] },
  { noc: "64401", title: "Postal services representatives", teer: 4, categories: [] },
  { noc: "64409", title: "Other customer and information services representatives", teer: 4, categories: [] },
  { noc: "64410", title: "Security guards and related security service occupations", teer: 4, categories: [] },
  { noc: "65100", title: "Cashiers", teer: 5, categories: [] },
  { noc: "65101", title: "Service station attendants", teer: 5, categories: [] },
  { noc: "65102", title: "Store shelf stockers, clerks and order fillers", teer: 5, categories: [] },
  { noc: "65109", title: "Other sales related occupations", teer: 5, categories: [] },
  { noc: "65200", title: "Food and beverage servers", teer: 5, categories: [] },
  { noc: "65201", title: "Food counter attendants, kitchen helpers and related support occupations", teer: 5, categories: [] },
  { noc: "65202", title: "Meat cutters and fishmongers - retail and wholesale", teer: 5, categories: [] },
  { noc: "65210", title: "Support occupations in accommodation, travel and facilities set-up services", teer: 5, categories: [] },
  { noc: "65211", title: "Operators and attendants in amusement, recreation and sport", teer: 5, categories: [] },
  { noc: "65220", title: "Pet groomers and animal care workers", teer: 5, categories: [] },
  { noc: "65229", title: "Other support occupations in personal services", teer: 5, categories: [] },
  { noc: "65310", title: "Light duty cleaners", teer: 5, categories: [] },
  { noc: "65311", title: "Specialized cleaners", teer: 5, categories: [] },
  { noc: "65312", title: "Janitors, caretakers and heavy-duty cleaners", teer: 5, categories: [] },
  { noc: "65320", title: "Dry cleaning, laundry and related occupations", teer: 5, categories: [] },
  { noc: "65329", title: "Other service support occupations", teer: 5, categories: [] },
  { noc: "70010", title: "Construction managers", teer: 0, categories: ["trades"] },
  { noc: "70011", title: "Home building and renovation managers", teer: 0, categories: ["trades"] },
  { noc: "70012", title: "Facility operation and maintenance managers", teer: 0, categories: [] },
  { noc: "70020", title: "Managers in transportation", teer: 0, categories: [] },
  { noc: "70021", title: "Postal and courier services managers", teer: 0, categories: [] },
  { noc: "72010", title: "Contractors and supervisors, machining, metal forming, shaping and erecting trades and related occupations", teer: 2, categories: [] },
  { noc: "72011", title: "Contractors and supervisors, electrical trades and telecommunications occupations", teer: 2, categories: [] },
  { noc: "72012", title: "Contractors and supervisors, pipefitting trades", teer: 2, categories: [] },
  { noc: "72013", title: "Contractors and supervisors, carpentry trades", teer: 2, categories: [] },
  { noc: "72014", title: "Contractors and supervisors, other construction trades, installers, repairers and servicers", teer: 2, categories: [] },
  { noc: "72020", title: "Contractors and supervisors, mechanic trades", teer: 2, categories: [] },
  { noc: "72021", title: "Contractors and supervisors, heavy equipment operator crews", teer: 2, categories: [] },
  { noc: "72022", title: "Supervisors, printing and related occupations", teer: 2, categories: [] },
  { noc: "72023", title: "Supervisors, railway transport operations", teer: 2, categories: [] },
  { noc: "72024", title: "Supervisors, motor transport and other ground transit operators", teer: 2, categories: [] },
  { noc: "72025", title: "Supervisors, mail and message distribution occupations", teer: 2, categories: [] },
  { noc: "72100", title: "Machinists and machining and tooling inspectors", teer: 2, categories: ["trades"] },
  { noc: "72101", title: "Tool and die makers", teer: 2, categories: [] },
  { noc: "72102", title: "Sheet metal workers", teer: 2, categories: ["trades"] },
  { noc: "72103", title: "Boilermakers", teer: 2, categories: [] },
  { noc: "72104", title: "Structural metal and platework fabricators and fitters", teer: 2, categories: [] },
  { noc: "72105", title: "Ironworkers", teer: 2, categories: [] },
  { noc: "72106", title: "Welders and related machine operators", teer: 2, categories: ["trades"] },
  { noc: "72200", title: "Electricians (except industrial and power system)", teer: 2, categories: ["trades"] },
  { noc: "72201", title: "Industrial electricians", teer: 2, categories: ["trades"] },
  { noc: "72202", title: "Power system electricians", teer: 2, categories: [] },
  { noc: "72203", title: "Electrical power line and cable workers", teer: 2, categories: [] },
  { noc: "72204", title: "Telecommunications line and cable installers and repairers", teer: 2, categories: [] },
  { noc: "72205", title: "Telecommunications equipment installation and cable television service technicians", teer: 2, categories: [] },
  { noc: "72300", title: "Plumbers", teer: 2, categories: ["trades"] },
  { noc: "72301", title: "Steamfitters, pipefitters and sprinkler system installers", teer: 2, categories: [] },
  { noc: "72302", title: "Gas fitters", teer: 2, categories: ["trades"] },
  { noc: "72310", title: "Carpenters", teer: 2, categories: ["trades"] },
  { noc: "72311", title: "Cabinetmakers", teer: 2, categories: ["trades"] },
  { noc: "72320", title: "Bricklayers", teer: 2, categories: ["trades"] },
  { noc: "72321", title: "Insulators", teer: 2, categories: [] },
  { noc: "72400", title: "Construction millwrights and industrial mechanics", teer: 2, categories: ["trades"] },
  { noc: "72401", title: "Heavy-duty equipment mechanics", teer: 2, categories: ["trades"] },
  { noc: "72402", title: "Heating, refrigeration and air conditioning mechanics", teer: 2, categories: ["trades"] },
  { noc: "72403", title: "Railway carmen/women", teer: 2, categories: [] },
  { noc: "72404", title: "Aircraft mechanics and aircraft inspectors", teer: 2, categories: ["transport"] },
  { noc: "72405", title: "Machine fitters", teer: 2, categories: [] },
  { noc: "72406", title: "Elevator constructors and mechanics", teer: 2, categories: [] },
  { noc: "72410", title: "Automotive service technicians, truck and bus mechanics and mechanical repairers", teer: 2, categories: ["transport"] },
  { noc: "72411", title: "Auto body collision, refinishing and glass technicians and damage repair estimators", teer: 2, categories: [] },
  { noc: "72420", title: "Oil and solid fuel heating mechanics", teer: 2, categories: [] },
  { noc: "72421", title: "Appliance servicers and repairers", teer: 2, categories: [] },
  { noc: "72422", title: "Electrical mechanics", teer: 2, categories: ["trades"] },
  { noc: "72423", title: "Motorcycle, all-terrain vehicle and other related mechanics", teer: 2, categories: [] },
  { noc: "72429", title: "Other small engine and small equipment repairers", teer: 2, categories: [] },
  { noc: "72500", title: "Crane operators", teer: 2, categories: [] },
  { noc: "72501", title: "Water well drillers", teer: 2, categories: ["trades"] },
  { noc: "72600", title: "Air pilots, flight engineers and flying instructors", teer: 2, categories: ["transport"] },
  { noc: "72601", title: "Air traffic controllers and related occupations", teer: 2, categories: [] },
  { noc: "72602", title: "Deck officers, water transport", teer: 2, categories: [] },
  { noc: "72603", title: "Engineer officers, water transport", teer: 2, categories: [] },
  { noc: "72604", title: "Railway traffic controllers and marine traffic regulators", teer: 2, categories: [] },
  { noc: "72999", title: "Other technical trades and related occupations", teer: 2, categories: ["trades"] },
  { noc: "73100", title: "Concrete finishers", teer: 3, categories: ["trades"] },
  { noc: "73101", title: "Tilesetters", teer: 3, categories: [] },
  { noc: "73102", title: "Plasterers, drywall installers and finishers and lathers", teer: 3, categories: [] },
  { noc: "73110", title: "Roofers and shinglers", teer: 3, categories: ["trades"] },
  { noc: "73111", title: "Glaziers", teer: 3, categories: [] },
  { noc: "73112", title: "Painters and decorators (except interior decorators)", teer: 3, categories: ["trades"] },
  { noc: "73113", title: "Floor covering installers", teer: 3, categories: ["trades"] },
  { noc: "73200", title: "Residential and commercial installers and servicers", teer: 3, categories: [] },
  { noc: "73201", title: "General building maintenance workers and building superintendents", teer: 3, categories: [] },
  { noc: "73202", title: "Pest controllers and fumigators", teer: 3, categories: [] },
  { noc: "73209", title: "Other repairers and servicers", teer: 3, categories: [] },
  { noc: "73300", title: "Transport truck drivers", teer: 3, categories: [] },
  { noc: "73301", title: "Bus drivers, subway operators and other transit operators", teer: 3, categories: [] },
  { noc: "73310", title: "Railway and yard locomotive engineers", teer: 3, categories: [] },
  { noc: "73311", title: "Railway conductors and brakemen/women", teer: 3, categories: [] },
  { noc: "73400", title: "Heavy equipment operators", teer: 3, categories: [] },
  { noc: "73401", title: "Printing press operators", teer: 3, categories: [] },
  { noc: "73402", title: "Drillers and blasters - surface mining, quarrying and construction", teer: 3, categories: [] },
  { noc: "74100", title: "Mail and parcel sorters and related occupations", teer: 4, categories: [] },
  { noc: "74101", title: "Letter carriers", teer: 4, categories: [] },
  { noc: "74102", title: "Couriers and messengers", teer: 4, categories: [] },
  { noc: "74200", title: "Railway yard and track maintenance workers", teer: 4, categories: [] },
  { noc: "74201", title: "Water transport deck and engine room crew", teer: 4, categories: [] },
  { noc: "74202", title: "Air transport ramp attendants", teer: 4, categories: [] },
  { noc: "74203", title: "Automotive and heavy truck and equipment parts installers and servicers", teer: 4, categories: [] },
  { noc: "74204", title: "Utility maintenance workers", teer: 4, categories: [] },
  { noc: "74205", title: "Public works maintenance equipment operators and related workers", teer: 4, categories: [] },
  { noc: "75100", title: "Longshore workers", teer: 5, categories: [] },
  { noc: "75101", title: "Material handlers", teer: 5, categories: [] },
  { noc: "75110", title: "Construction trades helpers and labourers", teer: 5, categories: [] },
  { noc: "75119", title: "Other trades helpers and labourers", teer: 5, categories: [] },
  { noc: "75200", title: "Taxi and limousine drivers and chauffeurs", teer: 5, categories: [] },
  { noc: "75201", title: "Delivery service drivers and door-to-door distributors", teer: 5, categories: [] },
  { noc: "75210", title: "Boat and cable ferry operators and related occupations", teer: 5, categories: [] },
  { noc: "75211", title: "Railway and motor transport labourers", teer: 5, categories: [] },
  { noc: "75212", title: "Public works and maintenance labourers", teer: 5, categories: [] },
  { noc: "80010", title: "Managers in natural resources production and fishing", teer: 0, categories: [] },
  { noc: "80020", title: "Managers in agriculture", teer: 0, categories: [] },
  { noc: "80021", title: "Managers in horticulture", teer: 0, categories: [] },
  { noc: "80022", title: "Managers in aquaculture", teer: 0, categories: [] },
  { noc: "82010", title: "Supervisors, logging and forestry", teer: 2, categories: [] },
  { noc: "82020", title: "Supervisors, mining and quarrying", teer: 2, categories: [] },
  { noc: "82021", title: "Contractors and supervisors, oil and gas drilling and services", teer: 2, categories: ["trades"] },
  { noc: "82030", title: "Agricultural service contractors and farm supervisors", teer: 2, categories: [] },
  { noc: "82031", title: "Contractors and supervisors, landscaping, grounds maintenance and horticulture services", teer: 2, categories: [] },
  { noc: "83100", title: "Underground production and development miners", teer: 3, categories: [] },
  { noc: "83101", title: "Oil and gas well drillers, servicers, testers and related workers", teer: 3, categories: [] },
  { noc: "83110", title: "Logging machinery operators", teer: 3, categories: [] },
  { noc: "83120", title: "Fishing masters and officers", teer: 3, categories: [] },
  { noc: "83121", title: "Fishermen/women", teer: 3, categories: [] },
  { noc: "84100", title: "Underground mine service and support workers", teer: 4, categories: [] },
  { noc: "84101", title: "Oil and gas well drilling and related workers and services operators", teer: 4, categories: [] },
  { noc: "84110", title: "Chain saw and skidder operators", teer: 4, categories: [] },
  { noc: "84111", title: "Silviculture and forestry workers", teer: 4, categories: [] },
  { noc: "84120", title: "Specialized livestock workers and farm machinery operators", teer: 4, categories: [] },
  { noc: "84121", title: "Fishing vessel deckhands", teer: 4, categories: [] },
  { noc: "85100", title: "Livestock labourers", teer: 5, categories: [] },
  { noc: "85101", title: "Harvesting labourers", teer: 5, categories: [] },
  { noc: "85102", title: "Aquaculture and marine harvest labourers", teer: 5, categories: [] },
  { noc: "85103", title: "Nursery and greenhouse labourers", teer: 5, categories: [] },
  { noc: "85104", title: "Trappers and hunters", teer: 5, categories: [] },
  { noc: "85110", title: "Mine labourers", teer: 5, categories: [] },
  { noc: "85111", title: "Oil and gas drilling, servicing and related labourers", teer: 5, categories: [] },
  { noc: "85120", title: "Logging and forestry labourers", teer: 5, categories: [] },
  { noc: "85121", title: "Landscaping and grounds maintenance labourers", teer: 5, categories: [] },
  { noc: "90010", title: "Manufacturing managers", teer: 0, categories: [] },
  { noc: "90011", title: "Utilities managers", teer: 0, categories: [] },
  { noc: "92010", title: "Supervisors, mineral and metal processing", teer: 2, categories: [] },
  { noc: "92011", title: "Supervisors, petroleum, gas and chemical processing and utilities", teer: 2, categories: [] },
  { noc: "92012", title: "Supervisors, food and beverage processing", teer: 2, categories: [] },
  { noc: "92013", title: "Supervisors, plastic and rubber products manufacturing", teer: 2, categories: [] },
  { noc: "92014", title: "Supervisors, forest products processing", teer: 2, categories: [] },
  { noc: "92015", title: "Supervisors, textile, fabric, fur and leather products processing and manufacturing", teer: 2, categories: [] },
  { noc: "92020", title: "Supervisors, motor vehicle assembling", teer: 2, categories: [] },
  { noc: "92021", title: "Supervisors, electronics and electrical products manufacturing", teer: 2, categories: [] },
  { noc: "92022", title: "Supervisors, furniture and fixtures manufacturing", teer: 2, categories: [] },
  { noc: "92023", title: "Supervisors, other mechanical and metal products manufacturing", teer: 2, categories: [] },
  { noc: "92024", title: "Supervisors, other products manufacturing and assembly", teer: 2, categories: [] },
  { noc: "92100", title: "Power engineers and power systems operators", teer: 2, categories: [] },
  { noc: "92101", title: "Water and waste treatment plant operators", teer: 2, categories: [] },
  { noc: "93100", title: "Central control and process operators, mineral and metal processing", teer: 3, categories: [] },
  { noc: "93101", title: "Central control and process operators, petroleum, gas and chemical processing", teer: 3, categories: [] },
  { noc: "93102", title: "Pulping, papermaking and coating control operators", teer: 3, categories: [] },
  { noc: "93200", title: "Aircraft assemblers and aircraft assembly inspectors", teer: 3, categories: [] },
  { noc: "94100", title: "Machine operators, mineral and metal processing", teer: 4, categories: [] },
  { noc: "94101", title: "Foundry workers", teer: 4, categories: [] },
  { noc: "94102", title: "Glass forming and finishing machine operators and glass cutters", teer: 4, categories: [] },
  { noc: "94103", title: "Concrete, clay and stone forming operators", teer: 4, categories: [] },
  { noc: "94104", title: "Inspectors and testers, mineral and metal processing", teer: 4, categories: [] },
  { noc: "94105", title: "Metalworking and forging machine operators", teer: 4, categories: [] },
  { noc: "94106", title: "Machining tool operators", teer: 4, categories: [] },
  { noc: "94107", title: "Machine operators of other metal products", teer: 4, categories: [] },
  { noc: "94110", title: "Chemical plant machine operators", teer: 4, categories: [] },
  { noc: "94111", title: "Plastics processing machine operators", teer: 4, categories: [] },
  { noc: "94112", title: "Rubber processing machine operators and related workers", teer: 4, categories: [] },
  { noc: "94120", title: "Sawmill machine operators", teer: 4, categories: [] },
  { noc: "94121", title: "Pulp mill, papermaking and finishing machine operators", teer: 4, categories: [] },
  { noc: "94122", title: "Paper converting machine operators", teer: 4, categories: [] },
  { noc: "94123", title: "Lumber graders and other wood processing inspectors and graders", teer: 4, categories: [] },
  { noc: "94124", title: "Woodworking machine operators", teer: 4, categories: [] },
  { noc: "94129", title: "Other wood processing machine operators", teer: 4, categories: [] },
  { noc: "94130", title: "Textile fibre and yarn, hide and pelt processing machine operators and workers", teer: 4, categories: [] },
  { noc: "94131", title: "Weavers, knitters and other fabric making occupations", teer: 4, categories: [] },
  { noc: "94132", title: "Industrial sewing machine operators", teer: 4, categories: [] },
  { noc: "94133", title: "Inspectors and graders, textile, fabric, fur and leather products manufacturing", teer: 4, categories: [] },
  { noc: "94140", title: "Process control and machine operators, food and beverage processing", teer: 4, categories: [] },
  { noc: "94141", title: "Industrial butchers and meat cutters, poultry preparers and related workers", teer: 4, categories: [] },
  { noc: "94142", title: "Fish and seafood plant workers", teer: 4, categories: [] },
  { noc: "94143", title: "Testers and graders, food and beverage processing", teer: 4, categories: [] },
  { noc: "94150", title: "Plateless printing equipment operators", teer: 4, categories: [] },
  { noc: "94151", title: "Camera, platemaking and other prepress occupations", teer: 4, categories: [] },
  { noc: "94152", title: "Binding and finishing machine operators", teer: 4, categories: [] },
  { noc: "94153", title: "Photographic and film processors", teer: 4, categories: [] },
  { noc: "94200", title: "Motor vehicle assemblers, inspectors and testers", teer: 4, categories: [] },
  { noc: "94201", title: "Electronics assemblers, fabricators, inspectors and testers", teer: 4, categories: [] },
  { noc: "94202", title: "Assemblers and inspectors, electrical appliance, apparatus and equipment manufacturing", teer: 4, categories: [] },
  { noc: "94203", title: "Assemblers, fabricators and inspectors, industrial electrical motors and transformers", teer: 4, categories: [] },
  { noc: "94204", title: "Mechanical assemblers and inspectors", teer: 4, categories: [] },
  { noc: "94205", title: "Machine operators and inspectors, electrical apparatus manufacturing", teer: 4, categories: [] },
  { noc: "94210", title: "Furniture and fixture assemblers, finishers, refinishers and inspectors", teer: 4, categories: [] },
  { noc: "94211", title: "Assemblers and inspectors of other wood products", teer: 4, categories: [] },
  { noc: "94212", title: "Plastic products assemblers, finishers and inspectors", teer: 4, categories: [] },
  { noc: "94213", title: "Industrial painters, coaters and metal finishing process operators", teer: 4, categories: [] },
  { noc: "94219", title: "Other products assemblers, finishers and inspectors", teer: 4, categories: [] },
  { noc: "95100", title: "Labourers in mineral and metal processing", teer: 5, categories: [] },
  { noc: "95101", title: "Labourers in metal fabrication", teer: 5, categories: [] },
  { noc: "95102", title: "Labourers in chemical products processing and utilities", teer: 5, categories: [] },
  { noc: "95103", title: "Labourers in wood, pulp and paper processing", teer: 5, categories: [] },
  { noc: "95104", title: "Labourers in rubber and plastic products manufacturing", teer: 5, categories: [] },
  { noc: "95105", title: "Labourers in textile processing and cutting", teer: 5, categories: [] },
  { noc: "95106", title: "Labourers in food and beverage processing", teer: 5, categories: [] },
  { noc: "95107", title: "Labourers in fish and seafood processing", teer: 5, categories: [] },
  { noc: "95109", title: "Other labourers in processing, manufacturing and utilities", teer: 5, categories: [] },
];
